# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6bdceada6846abe7c781258bae04d71e2a2327ebbb7892df75c12c5ef3c44585ac0e4fdea7d1dbcccc32c98d38edfc36f1a3873f639f02f004dc171bc87f5b5

test:
  secret_key_base: a6af5e41220fc15b5226ad5a4b297c1c2e77dcb7f556da0ee9047454994f56d5056b330bb3c0a07b731cce8b4968689593bc7444a4fd903918da5729a554fe1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
